### ISSUE TITLE
Pykka error on mopidy start.

### ISSUE THREAD

**Issue by Tech-Geek97** [pimoroni/mopidy-pidi#19]
When I attempt to run Mopidy with this plugin my Pirate Audio display does not work. It seems to not be able to find a file or directory, but it does not seem to specify which file.

```
pi@MopidyPi:~ $ sudo journalctl -u mopidy
-- Logs begin at Thu 2019-02-14 04:11:59 CST, end at Tue 2021-06-22 12:06:25 CDT. --
Jun 22 12:03:44 MopidyPi systemd[1]: Starting Mopidy music server...
Jun 22 12:03:44 MopidyPi systemd[1]: Started Mopidy music server.
Jun 22 12:03:46 MopidyPi mopidy[535]: INFO     [MainThread] mopidy.__main__ Starting Mopidy 3.1.1
Jun 22 12:03:46 MopidyPi mopidy[535]: INFO     [MainThread] mopidy.config Loading config from builtin defaults
Jun 22 12:03:46 MopidyPi mopidy[535]: INFO     [MainThread] mopidy.config Loading config from file:///usr/share/mopidy/conf.d/mopidy.conf
Jun 22 12:03:46 MopidyPi mopidy[535]: INFO     [MainThread] mopidy.config Loading config from file:///etc/mopidy/mopidy.conf
Jun 22 12:03:46 MopidyPi mopidy[535]: INFO     [MainThread] mopidy.config Loading config from command line options
Jun 22 12:03:46 MopidyPi mopidy[535]: INFO     [MainThread] mopidy.__main__ Enabled extensions: raspberry-gpio, softwaremixer, ytmusic, stream, spotify, m3u, pidi, iris, file, http
Jun 22 12:03:46 MopidyPi mopidy[535]: INFO     [MainThread] mopidy.__main__ Disabled extensions: none
Jun 22 12:03:47 MopidyPi mopidy[535]: INFO     [MainThread] mopidy.commands Starting Mopidy mixer: SoftwareMixer
Jun 22 12:03:47 MopidyPi mopidy[535]: INFO     [MainThread] mopidy.commands Mixer volume set to 40
Jun 22 12:03:47 MopidyPi mopidy[535]: INFO     [MainThread] mopidy.commands Starting Mopidy audio
Jun 22 12:03:47 MopidyPi mopidy[535]: INFO     [MainThread] mopidy.commands Starting Mopidy backends: YTMusicBackend, FileBackend, M3UBackend, StreamBackend, SpotifyBackend
Jun 22 12:03:47 MopidyPi mopidy[535]: INFO     [Audio-2] mopidy.audio.actor Audio output set to "alsasink"
Jun 22 12:03:48 MopidyPi mopidy[535]: INFO     [SpotifyEventLoop] mopidy_spotify.backend Logged in to Spotify in online mode
Jun 22 12:03:49 MopidyPi mopidy[535]: INFO     [SpotifyBackend-9] mopidy_spotify.web Logged into Spotify Web API as 94w2qoj9oj6kykbt1xii2sqek
Jun 22 12:03:49 MopidyPi mopidy[535]: INFO     [Thread-4] mopidy_ytmusic YTMusic loaded 9 auto playlists sections
Jun 22 12:03:49 MopidyPi mopidy[535]: INFO     [Thread-4] mopidy_ytmusic YTMusic Auto Playlists refreshed in 1.74s
Jun 22 12:03:58 MopidyPi mopidy[535]: INFO     [SpotifyBackend-9] mopidy_spotify.playlists Refreshed 37 Spotify playlists
Jun 22 12:03:58 MopidyPi mopidy[535]: INFO     [SpotifyBackend-9] mopidy_spotify.backend Spotify private session activated
Jun 22 12:03:58 MopidyPi mopidy[535]: INFO     [MainThread] mopidy.commands Starting Mopidy core
Jun 22 12:03:58 MopidyPi mopidy[535]: INFO     [MainThread] mopidy.commands Starting Mopidy frontends: YTMusicScrobbleFE, RaspberryGPIOFrontend, PiDiFrontend, IrisFrontend, HttpFrontend
Jun 22 12:03:58 MopidyPi mopidy[535]: INFO     [IrisFrontend-16] mopidy_iris.core Starting Iris 3.58.0
Jun 22 12:03:58 MopidyPi mopidy[535]: INFO     [HttpFrontend-18] mopidy.http.actor HTTP server running at [::ffff:0.0.0.0]:6680
Jun 22 12:03:58 MopidyPi mopidy[535]: INFO     [MainThread] mopidy.commands Starting GLib mainloop
Jun 22 12:03:59 MopidyPi mopidy[535]: ERROR    [PiDiFrontend-15] pykka Unhandled exception in PiDiFrontend (urn:uuid:5bfb631f-59a8-425f-b739-76bc9f5a931a):
Jun 22 12:03:59 MopidyPi mopidy[535]: Traceback (most recent call last):
Jun 22 12:03:59 MopidyPi mopidy[535]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 186, in _actor_loop
Jun 22 12:03:59 MopidyPi mopidy[535]:     self.on_start()
Jun 22 12:03:59 MopidyPi mopidy[535]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_pidi/frontend.py", line 38, in on_start
Jun 22 12:03:59 MopidyPi mopidy[535]:     self.display = PiDi(self.config)
Jun 22 12:03:59 MopidyPi mopidy[535]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_pidi/frontend.py", line 179, in __init__
Jun 22 12:03:59 MopidyPi mopidy[535]:     self._display = self.display_class(self.display_config)
Jun 22 12:03:59 MopidyPi mopidy[535]:   File "/usr/local/lib/python3.7/dist-packages/pidi_display_st7789/__init__.py", line 21, in __init__
Jun 22 12:03:59 MopidyPi mopidy[535]:     spi_speed_hz=args.spi_speed_mhz * 1000 * 1000
Jun 22 12:03:59 MopidyPi mopidy[535]:   File "/usr/local/lib/python3.7/dist-packages/ST7789/__init__.py", line 118, in __init__
Jun 22 12:03:59 MopidyPi mopidy[535]:     self._spi = spidev.SpiDev(port, cs)
Jun 22 12:03:59 MopidyPi mopidy[535]: FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by Tech-Geek97** [comment]
I had not enabled SPI in raspi-config. See here for solution [https://learn.adafruit.com/adafruits-raspberry-pi-lesson-4-gpio-setup/configuring-spi](url)

**Comment by Gadgetoid** [comment]
Failure in my instructions/install scripts, perhaps?

**Comment by Tech-Geek97** [comment]
It would be useful if all of the pirate audio repo readmes linked to the general deployment guide as it covers dependencies. [https://github.com/pimoroni/pirate-audio/blob/master/mopidy/README.md](url)
